### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by Xmonpl** [SentixDev/Pl3xMap-Marker#9]
Plugin does not start correctly, the following error is displayed. https://mclo.gs/n57hweO

Server version : ``git-Purpur-1449 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91e3be5 on HEAD)``

SquareMap Version: ``1.1.0-SNAPSHOT+3c1fca1``

**Comment by SentixDev** [comment]
Jup the squaremap author did some API changes again, maybe I'll fix it later idk. Temporary solution is downgrading squaremap to an older version.

**Comment by SentixDev** [comment]
https://github.com/SentixDev/Pl3xMap-Marker/releases/tag/release-4.1-squaremap
